package sdk


const (
	MWM = 9
	Depth = 3
)

const (
	ENDPOINT ="http://202.117.43.212:14265"
	SEED           = "TX9XRR9SRCOBMTYDTMKNEIJCSZIMEUPWCNLC9DPDZKKAEMEFVSTEVUFTRUZXEHLULEIYJIEOWIC9STAHW"
	SIDEKEYPRIVATE = "QOLOACG9BNUYLERQTZPPW9VKIOPDRTPMFZCYWGNVKIZJEYBWJDXASOXNDMZGBNYFVBCFBQBXSCCAFFRIO"
)

